import ww from './logo/ww.png'
import ww_sm from './logo/ww_sm.png'
import ww_str from './logo/ww_logo_str.png'
import ww_str_sm from './logo/ww_logo_str_sm.png'
import ww_logo from './logo/ww_logo.png'
import ww_logo_sm from './logo/ww_logo_sm.png'
import ww_text from './logo/ww_text.png'
import ww_text_sm from './logo/ww_text_sm.png'
import contactIMG from './images/contactIMG.jpg'
export {ww,ww_sm,ww_str_sm,ww_str,ww_logo,ww_logo_sm,ww_text_sm,ww_text,contactIMG}